name: log4shell-goof-server Docker image build and test

on:
  push:
    branches:
      - 'main'
    paths:
      - 'log4shell-goof/log4shell-goof-server/**'
      - '.github/workflows/log4shell-goof-server-docker-image.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'log4shell-goof/log4shell-goof-server/**'
      - '.github/workflows/log4shell-goof-server-docker-image.yaml'
permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  contents: read
jobs:
  build-log4shell-server-image:
    runs-on: ubuntu-24.04
    env:
      DOCKER_REPO: 'marco-dev-docker'
      IMAGE_NAME: 'log4shell-goof:${{ github.run_number }}'
      JF_URL: https://${{ vars.JF_URL }}/
      DOCKER_CLI_EXPERIMENTAL: enabled
    defaults:
      run:
        working-directory: log4shell-goof/log4shell-server
    steps:
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli
        env:
          JF_URL: https://${{ vars.JF_URL }}/
          JF_PROJECT: ${{ vars.JF_PROJECT }}
        with:
            oidc-provider-name: github-oidc-marco

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3                 

      - name: Authenticate Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.JF_URL }}
          username: ${{ steps.setup-cli.outputs.oidc-user }}
          password: ${{ steps.setup-cli.outputs.oidc-token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: docker CLI build
        run: |
          docker buildx ls
          jf docker --version
          jf docker build --tag ${{ vars.JF_URL }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME}} --platform linux/amd64 --metadata-file metadata.json --push .

      # - name: Build
      #   uses: docker/build-push-action@v2
      #   with:
      #     load: true
      #     context: log4shell-goof/log4shell-server
      #     push: true
      #     tags: log4shell-server:latest
          
      - name: docker scan
        run: |  
            jf docker pull ${{ vars.JF_URL }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}
            jf docker scan ${{ vars.JF_URL }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}   

      - name: publish build info
        run: |
          jf rt build-collect-env 
          jf rt build-add-dependencies .
          jf rt build-add-git
          jf rt build-publish

      - name: build scan
        run: |
          echo "sleeping for 45 seconds"
          sleep 45
          echo "waking up."
          jf build-scan

      - name: Run container
        run: docker run -d --rm --name log4shell-server log4shell-server:latest && sleep 5

      - name: Smoke test LDAP running in container
        run: docker logs log4shell-server | grep "LDAP server listening on 0.0.0.0:8000"

      - name: Smoke test HTTP running in container
        run: docker logs log4shell-server | grep "HTTP server listening on 0.0.0.0:9999"

      - name: Cleanup container
        run: docker kill log4shell-server

      # - name: Start minikube
      #   uses: medyagh/setup-minikube@master
      #   with:
      #     cni: calico

      # - name: Deploy to minikube
      #   run: |
      #     sed -i 's/${DOCKER_ACCOUNT}\///' k8s/deploy.yaml
      #     sed -i 's/imagePullPolicy: Always/imagePullPolicy: Never/' k8s/deploy.yaml
      #     minikube image load log4shell-server:latest
      #     kubectl apply -f k8s/deploy.yaml

      # - name: Test pods came up cleanly
      #   run: |
      #     kubectl get all --namespace=darkweb && \
      #     kubectl wait --namespace=darkweb --for=condition=ready pod --selector=app=log4shell --timeout=90s

      # - name: Dump pod description
      #   if: ${{ failure() }}
      #   run: |
      #     kubectl describe pod --namespace=darkweb --selector=app=log4shell
      #     kubectl describe deploy --namespace=darkweb --selector=app=log4shell
      - name: Write to workflow job summary
        run: |
              NOTE=$'>[!NOTE]\n>Frog Notes \n'
              TIP=$'>[!TIP]\n>Hello JFrog\n'
              IMPORTANT=$'>[!IMPORTANT]\n>Hello IMPORTANT NOTE\n'
              WARNING=$'>[!WARNING]\n>Hello WARNING NOTE\n'
              CAUTION=$'>[!CAUTION]\n>Hello CAUTION NOTE\n'
              echo "$NOTE" >> $GITHUB_STEP_SUMMARY
              echo "$TIP" >> $GITHUB_STEP_SUMMARY
              echo "$IMPORTANT" >> $GITHUB_STEP_SUMMARY
              echo "$WARNING" >> $GITHUB_STEP_SUMMARY
              echo "$CAUTION" >> $GITHUB_STEP_SUMMARY
